ViewModels/PedidoLancheViewModel.cs
using VL_VendasLanches.Models;

namespace VL_VendasLanches.ViewModels
{
    public class PedidoLancheViewModel
    {
        public Pedido Pedido { get; set; }
        public IEnumerable<PedidoDetalhe> PedidoDetalhes{ get; set; }
    }
}

Areas/Admin/Controllers/AdminPedidosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VL_VendasLanches.Context;
using VL_VendasLanches.Models;
using VL_VendasLanches.Repositories.Interfaces;
using VL_VendasLanches.ViewModels;

namespace VL_VendasLanches.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize("Admin")] // tem que estar com perfi de admin
    public class AdminPedidosController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IPedidoRepository _pedidoRepository;

        public AdminPedidosController(AppDbContext context, IPedidoRepository pedidoRepository)
        {
            _context = context;
            _pedidoRepository = pedidoRepository;
        }

        public IActionResult PedidoLanches(Guid? id)
        {
            var pedido = _context.Pedidos
                         .Include(pd => pd.PedidoItens)
                         .ThenInclude(l => l.Produto)
                         .FirstOrDefault(p => p.Id == id);

            if (pedido == null)
            {
                Response.StatusCode = 404;
                return View("PedidoNotFound", id.Value);
            }

            PedidoLancheViewModel pedidoLanches = new PedidoLancheViewModel()
            {
                Pedido = pedido,
                PedidoDetalhes = pedido.PedidoItens
            };
            return View(pedidoLanches);
        }

        //Consulta com paginação utilizando ReflectionIT.Mvc.Paging;
        public async Task<IActionResult> Index([FromQuery] int ps = 3, [FromQuery] int page = 1, [FromQuery] string q = null)
        {
            var pedidos = _pedidoRepository.Get();
            //var pedidos = _context.Pedidos.AsQueryable().AsNoTracking(); igual a linha de cima

            pedidos = pedidos.OrderBy(o => o.Nome);

            if (!string.IsNullOrEmpty(q))
            {
                pedidos = pedidos.Where(o => o.Nome.Contains(q));
            }
            var paginacaoPedidos = await _pedidoRepository.ObterTodos(pedidos, page, ps, q);

            #region
            //var resultado = _context.Pedidos.AsNoTracking().AsQueryable();

            //if (!string.IsNullOrWhiteSpace(filter))
            //{
            //    resultado = resultado.Where(p => p.Nome.Contains(filter));
            //}

            //var model = await PagingList.CreateAsync(resultado, 3, pageindex, sort, "Nome");
            //model.RouteValue = new RouteValueDictionary { { "filter", filter } }; //padrao do componente, utilizar na view
            #endregion

            return View(paginacaoPedidos);
        }

        // GET: Admin/AdminPedidos/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // GET: Admin/AdminPedidos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminPedidos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PedidoId,Nome,Sobrenome,Endereco,Numero,Cep,Estado,Cidade,Telefone,Email,PedidoEnviado,PedidoEntregueEm")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pedido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pedido);
        }

        // GET: Admin/AdminPedidos/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido == null)
            {
                return NotFound();
            }
            return View(pedido);
        }

        // POST: Admin/AdminPedidos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("PedidoId,Nome,Sobrenome,Endereco,Numero,Cep,Estado,Cidade,Telefone,Email,PedidoEnviado,PedidoEntregueEm")] Pedido pedido)
        {
            if (id != pedido.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pedido);
        }

        // GET: Admin/AdminPedidos/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // POST: Admin/AdminPedidos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var pedido = await _context.Pedidos.FindAsync(id);
            _context.Pedidos.Remove(pedido);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoExists(Guid id)
        {
            return _context.Pedidos.Any(e => e.Id == id);
        }
    }
}

Areas/Admin/Views/AdminPedidos/Create.cshtml
@model VL_VendasLanches.Models.Pedido

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco" class="control-label"></label>
                <input asp-for="Endereco" class="form-control" />
                <span asp-validation-for="Endereco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Numero" class="control-label"></label>
                <input asp-for="Numero" class="form-control" />
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cep" class="control-label"></label>
                <input asp-for="Cep" class="form-control" />
                <span asp-validation-for="Cep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PedidoEnviado" class="control-label"></label>
                <input asp-for="PedidoEnviado" class="form-control" />
                <span asp-validation-for="PedidoEnviado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PedidoEntregueEm" class="control-label"></label>
                <input asp-for="PedidoEntregueEm" class="form-control" />
                <span asp-validation-for="PedidoEntregueEm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/AdminPedidos/Delete.cshtml
@model VL_VendasLanches.Models.Pedido

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Endereco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Numero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Numero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cep)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cep)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PedidoEnviado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PedidoEnviado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PedidoEntregueEm)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PedidoEntregueEm)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Areas/Admin/Views/AdminPedidos/Details.cshtml
@model VL_VendasLanches.Models.Pedido

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sobrenome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sobrenome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Endereco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Numero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Numero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cep)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cep)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cidade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PedidoEnviado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PedidoEnviado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PedidoEntregueEm)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PedidoEntregueEm)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/AdminPedidos/Edit.cshtml
@model VL_VendasLanches.Models.Pedido

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Endereco" class="control-label"></label>
                <input asp-for="Endereco" class="form-control" />
                <span asp-validation-for="Endereco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Numero" class="control-label"></label>
                <input asp-for="Numero" class="form-control" />
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cep" class="control-label"></label>
                <input asp-for="Cep" class="form-control" />
                <span asp-validation-for="Cep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cidade" class="control-label"></label>
                <input asp-for="Cidade" class="form-control" />
                <span asp-validation-for="Cidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PedidoEnviado" class="control-label"></label>
                <input asp-for="PedidoEnviado" class="form-control" />
                <span asp-validation-for="PedidoEnviado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PedidoEntregueEm" class="control-label"></label>
                <input asp-for="PedidoEntregueEm" class="form-control" />
                <span asp-validation-for="PedidoEntregueEm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/AdminPedidos/Index.cshtml
@model VL_VendasLanches.ViewModels.PagedViewModel<Pedido>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

@*<form method="get" class="form-inline">

    <input name="filter" class="form-control" placeholder="filtro"
    value="@Model.RouteValue["Filter"]" />

    <button type="submit" class="btn btn-info">Procurar</button>
    </form>*@

<form method="get" asp-controller="AdminPedidos" asp-action="Index" class="search">
    <div class="input-group w-100">
        <input type="text" id="q" name="q" class="form-control" value="@ViewBag.Pesquisa" placeholder="O que você está procurando?">
        <div class="input-group-append">
            <button class="btn btn-primary" type="submit">
                <i class="fa fa-search"></i>
            </button>
        </div>
    </div>
</form>

Total de Pedidos : @Model.TotalResults
@*<div>
    <vc:pager paging-list="@Model"></vc:pager>
    </div>*@

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Nome
                @*@Html.DisplayNameFor(model => model.List.)*@
            </th>
            <th>
                Sobrenome
                @*@Html.DisplayNameFor(model => model.Sobrenome)*@
            </th>
            <th>
                Endereço 1
                @*@Html.DisplayNameFor(model => model.Endereco1)*@
            </th>
            <th>
                Endereço 2
                @*@Html.DisplayNameFor(model => model.Endereco2)*@
            </th>
            <th>
                Cep
                @*@Html.DisplayNameFor(model => model.Cep)*@
            </th>
            <th>
                Estado
                @*@Html.DisplayNameFor(model => model.Estado)*@
            </th>
            <th>
                Cidade
                @*@Html.DisplayNameFor(model => model.Cidade)*@
            </th>
            <th>
                Telefone
                @*@Html.DisplayNameFor(model => model.Telefone)*@
            </th>
            <th>
                Email
                @*@Html.DisplayNameFor(model => model.Email)*@
            </th>
            <th>
                Pedido Enviado
                @*@Html.DisplayNameFor(model => model.PedidoEnviado)*@
            </th>
            <th>
                Pedido Entregue
                @*                @Html.DisplayNameFor(model => model.PedidoEntregueEm)
                *@
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.List)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sobrenome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Endereco)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Numero)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cep)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PedidoEnviado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PedidoEntregueEm)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    <a asp-action="PedidoLanches" asp-route-id="@item.Id">Ver Itens</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<vc:paginacao modelo-paginado="@Model"></vc:paginacao>

Areas/Admin/Views/AdminPedidos/PedidoLanches.cshtml
@model VL_VendasLanches.ViewModels.PedidoLancheViewModel

@{
    ViewData["Title"] = "PedidoLanches";
    decimal totalPedido = 0;
}

<h1>Lanches do Pedido</h1>
<hr />

<h3>Pedido  :  @Html.DisplayFor(model => @Model.Pedido.Id)</h3>
<h3>Cliente :  @Html.DisplayFor(model => @Model.Pedido.Nome)</h3>
<h3>Data    :  @Html.DisplayFor(model => @Model.Pedido.PedidoEnviado)</h3>
<h3>Entrega :  @Html.DisplayFor(model => @Model.Pedido.PedidoEntregueEm)</h3>

<table class="table">
    @foreach (var item in @Model.Pedido.PedidoItens)
    {
        totalPedido += (@item.Produto.Preco * @item.Quantidade);
        <tr>
            <td align="right">
                <h3>@Html.DisplayFor(modelItem => item.Produto.Nome)</h3>
            </td>
            <td align="right">
                <img src="@item.Produto.ImagemUrl" class="img-fluid" height="100" width="100">
            </td>
            <td align="right">
                <h3>@string.Format("{0:C}", item.Produto.Preco)</h3>
            </td>
            <td align="right">
                <h3>(@Html.DisplayFor(modelItem => item.Quantidade))</h3>
            </td>
        </tr>
    }
    <tr>
        <td colspan="2">&nbsp;</td>
        <td align="right">
            <h3>Total do Pedido : @string.Format("{0:C}", @totalPedido)</h3>
        </td>
    </tr>
</table>
<a asp-action="Index" class="btn btn-outline-info">Retornar</a>

Areas/Admin/Views/AdminPedidos/PedidoNotFound.cshtml
@model int

@{
    ViewData["Title"] = "404 Not Found";
}

<div class="alert alert-danger mt-1 mb-1">
    <h1>Erro 404 - Not Found </h1>
    <hr />
    <h2>
        Pedido com o id = @Model não foi encontrado 
    </h2>
</div>

<a asp-action="Index" asp-controller="AdminPedidos" class="btn btn-outline-success">
    <h2>Retornar para a lista de Pedidos</h2>
</a>