Controllers/LancheController.cs
using Microsoft.AspNetCore.Mvc;
using VL_VendasLanches.Models;
using VL_VendasLanches.Repositories.Interfaces;
using VL_VendasLanches.Services.Interfaces;
using VL_VendasLanches.ViewModels;

namespace VL_VendasLanches.Controllers
{
    public class LancheController : Controller
    {
        private readonly IProdutoService _produtoService;

        public LancheController(IProdutoService produtoService)
        {
            _produtoService = produtoService;
        }

        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> List(string categoria)
        {
            #region
            //ViewData["Titulo"] = "Todos os lanches";    //atribuindo valor na ViewData para ser recuperado na view List 
            //ViewData["Data"] = DateTime.Now;
            //ViewBag.TotalLanches = "Total Lanches:";    //atribuindo valor na ViewBag para ser recuperado na view List , viewbag eh mais usado, porem viewData um pouco mais rapido
            //ViewBag.TotalLanchesCount = lanches.Count();
            #endregion
            return View(await _produtoService.ObterListaProdutoPorCategoria(categoria).ConfigureAwait(false));
        }

        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Details(Guid lancheId) =>
             View(await _produtoService.ObterProdutoPorId(lancheId).ConfigureAwait(false));

        [AutoValidateAntiforgeryToken]
        //viewResult retorna espeficiamente uma view
        public async Task<ViewResult> Search(string palavraChave)
        {
            //~ significa raiz, e escolhendo a view que sera passada
            return View("~/Views/Lanche/List.cshtml", await _produtoService.PesquisarProduto(palavraChave).ConfigureAwait(false));
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CarrinhoAtualizar(ProdutoCarrinhoAtualizarViewModel produtoAtualizarCarrinhoViewModel)
        {
            var produto = await _produtoService.ObterProdutoPorId(produtoAtualizarCarrinhoViewModel.ProdutoId).ConfigureAwait(false);
            produto.observacao = produtoAtualizarCarrinhoViewModel.Observacao;
            produto.TamanhoId = produtoAtualizarCarrinhoViewModel.TamanhoId;
            produto.quantidade = produtoAtualizarCarrinhoViewModel.Quantidade;
            return View("~/Views/Lanche/Details.cshtml", produto);
        }
    }
}

Views/Lanche/Details.cshtml
@using VL_VendasLanches.Extensions
@model ProdutoViewModel

<form method="post" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra">
    <input type="hidden" asp-for="@Model.Id" name="Id" />
    <div class="pt-4">
        <div class="card container" style="border:1px solid #808080;">
            <div class="card-header text-light row" style="border-radius: 0px;">
                <div class="col-12 col-md-9">
                    <h1 class="text-dark">@Model.Nome</h1>
                </div>
                <div class="col-12 col-md-3 text-end">
                    <h1 class="text-warning">@this.FormatoMoeda(Model.Preco ?? 0)</h1>
                </div>
            </div>
            <div class="card-body">
                <div class="container rounded p-2">
                    <div class="row">
                        <div class="col-12 col-lg-4 p-1 text-center">
                            <img src="@Model.ImagemUrl" style="border-radius: 35px;" width="100%" class="rounded" />
                        </div>
                        <div class="col-12 col-lg-8">
                            <div class="row pl-3">
                                <div class="col-12">
                                    @* <span class="badge badge-primary text-success p-3 border">
                                    @Model.
                                    </span>*@
                                    <h3 class="text-success"></h3>
                                    <p class="text-secondary"></p>
                                    <p>@Html.Raw(Model.DescricaoDetalhada)</p>
                                </div>
                            </div>
                            <!--Selecionar Tamanho do lanche-->
                            @if (Model.ExisteTamanho)
                            {
                                <div class="row text-bottom" style="">
                                    <div class="form-group col-md-4">
                                        <label class="control-label" style="margin-bottom: 10px">Selecione o Tamanho:</label>
                                    </div>
                                    <div class="form-group col-md-4">
                                        <select id="TamanhoDoProdutoSelecionado" name="TamanhoId" class="form-select form-select-sm" aria-label=".form-select-sm example">
                                            @foreach (var tamanho in Model.Tamanhos)
                                            {
                                                <option value="@tamanho.TamanhoId">@tamanho.Tamanho.TamanhoEnum</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            }
                            </br>
                            <div class="row">
                                <div class="form-group col-md-2">
                                    <label asp-for=" @Model.quantidade" class="control-label"></label>
                                    <input asp-for=" @Model.quantidade" type="number" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*?)\..*/g, '$1');" class="form-control"/>
                                    <span asp-validation-for=" @Model.quantidade" class="text-danger"></span>
                                </div>
                                <div class="form-group col-md-6">
                                    <label asp-for=" @Model.observacao" class="control-label"></label>
                                    <textarea asp-for="@Model.observacao" class="form-control"></textarea>
                                    <span asp-validation-for="@Model.observacao" class="text-danger"></span>
                                </div>
                            </div>
                            <!--Selecionar Tamanho do lanche-->
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="card-footer row d-flex justify-content-center">
                    <div class="d-grid gap-2 col-md-6">
                        <button class="btn btn-success flex-end" type="submit" id="AdicionarItemNoCarrinhoCompra" style="">Adicionar</button>
                        <a class="btn btn-warning" asp-controller="Lanche" asp-action="List">Voltar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Views/Lanche/List.cshtml
@model ProdutoListViewModel //View fortemente tipada que é de lanche, usado para criar a view

@*@{
    Layout = null; // Remove o layout padrão que é compartilhado, assim é possivel fazer layout personalizado somente para essa view
    }*@

<div>

    <br />
    <h2>Categoria: @Model.CategoriaAtual</h2>
    <br />

    @*    <br />
        <h2>@ViewData["Titulo"]</h2>
        <br />
        <h2>@ViewData["Data"]</h2>
        <hr />
        <h6>@ViewBag.TotalLanches @ViewBag.TotalLanchescount</h6>
        <hr />*@
</div>

@*<p>@TempData["Nome"]</p>*@

@*3 objetos para 3 coluna, g-4 define a margem*@
<div class="row">
    @foreach (var lanche in Model.Lanches)
    {
        <partial name="_LanchesResumo" for="@lanche" />//passa o lanche do for para a model da partial view
    }
    </div> 