Models/CarrinhoCompra.cs
using Microsoft.EntityFrameworkCore;
using VL_VendasLanches.Context;
using VL_VendasLanches.ViewModels;

namespace VL_VendasLanches.Models
{
    public class CarrinhoCompra
    {
        private readonly AppDbContext _context;

        public CarrinhoCompra(AppDbContext appContext) =>
            _context = appContext;

        public string CarrinhoCompraId { get; set; }
        public List<CarrinhoCompraItem> CarrinhoCompraItens { get; set; }

        public static CarrinhoCompra GetCarrinho(IServiceProvider services)
        {
            //Define uma sessao
            ISession session = services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;

            //obtem um servico do tipo do nosso contexto
            var context = services.GetService<AppDbContext>();

            //obtem ou gera id do carrinho
            string carrinhoId = session.GetString("CarrinhoId") ?? Guid.NewGuid().ToString();

            //atribui o id do carrinho na sessao
            session.SetString("CarrinhoId", carrinhoId);

            //retorna carrinho com contexto e o Id atribuido ou obtido
            return new CarrinhoCompra(context)
            {
                CarrinhoCompraId = carrinhoId,
            };
        }

        public async Task AdicionarCarrinho(Produto lanche, ProdutoViewModel produtoViewModel)
        {
            var carrinhoCompraItem = await _context.CarrinhoCompraItens.SingleOrDefaultAsync(
                                        s => s.Produto.Id.Equals(lanche.Id)
                                        && s.CarrinhoCompraId.Equals(CarrinhoCompraId)).ConfigureAwait(false);

            if (carrinhoCompraItem == null)
            {
                carrinhoCompraItem = new CarrinhoCompraItem
                {
                    CarrinhoCompraId = CarrinhoCompraId,
                    Produto = lanche,
                    Quantidade = produtoViewModel.quantidade,
                    TamanhoId = produtoViewModel.TamanhoId,
                    Observacao = produtoViewModel.observacao
                };

                _context.CarrinhoCompraItens.Add(carrinhoCompraItem);
            }
            else
            {
                carrinhoCompraItem.Produto = lanche;
                carrinhoCompraItem.Quantidade = produtoViewModel.quantidade;
                carrinhoCompraItem.TamanhoId = produtoViewModel.TamanhoId;
                carrinhoCompraItem.Observacao = produtoViewModel.observacao;
            }

            await _context.SaveChangesAsync().ConfigureAwait(false);
        }

        public async Task AtualizarCarrinho(CarrinhoCompraItem carrinhoCompraItem)
        {
            _context.Update(carrinhoCompraItem);
            await _context.SaveChangesAsync().ConfigureAwait(false);
        }

        public async Task RemoverDoCarrinho(Produto lanche)
        {
            var carrinhoCompraItem = await _context.CarrinhoCompraItens
                .SingleOrDefaultAsync(s => s.Produto.Id.Equals(lanche.Id)
                && s.CarrinhoCompraId.Equals(CarrinhoCompraId))
                .ConfigureAwait(false);

            if (carrinhoCompraItem != null)
            {
                _context.CarrinhoCompraItens.Remove(carrinhoCompraItem);
            }

            await _context.SaveChangesAsync().ConfigureAwait(false);
        }

        public async Task<List<CarrinhoCompraItem>> GetCarrinhoCompraItens()
        {
            return CarrinhoCompraItens ?? (CarrinhoCompraItens = await _context.CarrinhoCompraItens
                                            .Include(s => s.Produto)
                                            .Include(s => s.Produto.Tamanhos.OrderBy(s => s.Tamanho.TamanhoEnum))
                                            .ThenInclude(s => s.Tamanho)
                                            .Where(c => c.CarrinhoCompraId.Equals(CarrinhoCompraId))
                                            .ToListAsync().ConfigureAwait(false));
        }

        public List<CarrinhoCompraItem> GetCarrinhoCompraItensSincrono()
        {
            return CarrinhoCompraItens ?? (CarrinhoCompraItens = _context.CarrinhoCompraItens
                                            .Include(s => s.Produto)
                                            .Where(c => c.CarrinhoCompraId.Equals(CarrinhoCompraId))
                                            .ToList());
        }

        public void LimparCarrinho()
        {
            var carrinhoItens = _context.CarrinhoCompraItens
                                    .Where(carrinho => carrinho.CarrinhoCompraId.Equals(CarrinhoCompraId));

            _context.CarrinhoCompraItens.RemoveRange(carrinhoItens);
            _context.SaveChanges();
        }

        public async Task<decimal> GetCarrinhoCompraTotal()
        {
            return await _context.CarrinhoCompraItens
                        .Where(c => c.CarrinhoCompraId.Equals(CarrinhoCompraId))
                        .Select(c => c.Produto.Preco * c.Quantidade).SumAsync();
        }
    }
}

ViewModels/CarrinhoCompraViewModel.cs
using VL_VendasLanches.Models;

namespace VL_VendasLanches.ViewModels
{
    public class CarrinhoCompraViewModel
    {
        public CarrinhoCompra CarrinhoCompra { get; set; }
        public decimal CarrinhoCompraTotal { get; set; }

        public CarrinhoCompraViewModel() {}
        
        public CarrinhoCompraViewModel(CarrinhoCompra carrinhoCompra, decimal carrinhoCompraTotal)
        {
            CarrinhoCompra=carrinhoCompra;
            CarrinhoCompraTotal=carrinhoCompraTotal;
        }
    }
}

Controllers/CarrinhoCompraController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using VL_VendasLanches.Services.Interfaces;
using VL_VendasLanches.ViewModels;

namespace VL_VendasLanches.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly ICarrinhoCompraService _carrinhoCompraService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CarrinhoCompraController(ICarrinhoCompraService carrinhoCompraService,
            IHttpContextAccessor httpContextAccessor)
        {
            _carrinhoCompraService = carrinhoCompraService;
            _httpContextAccessor = httpContextAccessor;
        }
        [HttpGet]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Carrinho()
        {
            var carrinho = await _carrinhoCompraService.RecuperarCarrinho().ConfigureAwait(false);
            return View(carrinho);
        }

        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> AdicionarItemNoCarrinhoCompra(ProdutoViewModel produtoViewModel)
        {
            await _carrinhoCompraService.AdicionarItemNoCarrinhoCompra(produtoViewModel).ConfigureAwait(false);
            return RedirectToAction("Carrinho");
        }

        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> RemoverItemDoCarrinhoCompra(Guid lancheId)
        {
            await _carrinhoCompraService.RemoverItemCarrinhoCompra(lancheId).ConfigureAwait(false);
            return RedirectToAction("Carrinho");
        }
    }
}

Views/CarrinhoCompra/Carrinho.cshtml
@using VL_VendasLanches.Extensions
@model CarrinhoCompraViewModel //ViewImports tem um using para o import, assim a importação fica disponivel para aplicação toda

<div>
    <div class="card border mt-4 container">
        <div class="card-header bg-dark text-light ml-0 row">
            <div class="col-6">
                <i class="fa fa-shopping-cart"></i> &nbsp;
                GCN
            </div>
            <div class="col-6 text-end">
                <a asp-action="Index" asp-controller="Home" class="btn btn-outline-warning btn-sm">
                    Continuar comprando
                </a>
            </div>
        </div>
        <div class="card-body">
            <vc:Summary></vc:Summary>
            <div class="d-none d-lg-block">
                <div class="row text-info">
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-5">
                        Product Detalhe
                    </div>
                    <div class="col-lg-2">
                        Preço
                    </div>
                    <div class="col-lg-2">
                        Quantidade
                    </div>
                    <div class="col-lg-1">
                    </div>
                </div>
            </div>

            <hr />

            @foreach (var item in Model.CarrinhoCompra.CarrinhoCompraItens)
            {
                <div class="row h-100">
                    <div class="col-4 col-md-2 text-center py-2">
                        <img src="@item.Produto.ImagemUrl" class="rounded" width="100%" />
                    </div>
                    <div class="col-8 col-md-5">
                        <h5>@item.Produto.Nome</h5>
                        <div style="font-size:11px;">
                            @Html.Raw(item.Produto.DescricaoCurta)
                        </div>
                        <div style="font-size:11px;">
                            @Html.Raw("Observação("+item.Observacao+")")
                        </div>
                    </div>
                    <div class="col-3 col-md-2 pt-md-4" style="font-size:11px;">
                        <span style="font-size:17px;">
                            @string.Format("{0:c}", item.Produto.Preco)
                        </span>
                    </div>
                    <div class="col-3 col-md-2 pt-md-4" style="font-size:11px;">
                        <span style="font-size:17px;">
                            @item.Quantidade
                        </span>
                    </div>
                    <div class="col-2 col-lg-1 p-0 pt-lg-4 text-center">
                        <form asp-controller="Lanche" asp-action="CarrinhoAtualizar" method="post" role="form">
                            <input asp-for="@item.Produto.Id" name="ProdutoId" type="hidden" />
                            <input asp-for="@item.Observacao" name="Observacao" type="hidden" />
                            <input asp-for="@item.Quantidade" name="Quantidade" type="hidden" />
                            <input asp-for="@item.TamanhoId" name="TamanhoId" type="hidden" />
                            <button class="btn btn" type="submit" id="AtualizarProdutoCarrinho">
                                <i class="fa-solid fa-pencil fa-1x" style="color:blue"></i>
                            </button>
                            <a asp-controller="CarrinhoCompra" asp-action="RemoverItemDoCarrinhoCompra" asp-route-lancheId="@item.Produto.Id">
                                <i class="fa-solid fa-trash fa-1x" style="color:#d9534f"></i>
                            </a>
                        </form>
                    </div>
                </div>
                <hr />
            }
            <div class="row">
                <div class="col-6 text-end">
                    <span class="text-danger" style="font-size:21px;">
                        Total: @this.FormatoMoeda(Model.CarrinhoCompraTotal)
                        <br />
                    </span>
                </div>
            </div>
        </div>
        <div class="card-footer row">
            <div class="col-6 col-md-3 offset-md-6">
            </div>
            <div class="col-6 col-md-3">
                <a class="btn btn-success" asp-controller="Pedido" asp-action="Checkout">
                    <span>Encerrar Pedido</span>
                </a>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />

    <script type="text/javascript">
        function LimparValoresModal(quantidade) {
            $("#Quantidade").val(quantidade);
        }
    </script>
}